Adding a new student bio
HackYourFutureBelgium/class-13-14 pull request #55
Opened 2021-02-02 19:01 UTC by selimensar

2021-02-03 12:11 UTC, snicoll reviewed
Well done on filling the template. I've added a couple comments.

2021-02-03 12:11 UTC, snicoll commented on student-bios/selimensar.md
> +<div align="center">
While it's not technically wrong, it's a bit unusual to use html entries like that in a markdown file.  See [this guide](https://guides.github.com/features/mastering-markdown/) for tips & tricks, including some GitHub specific features.

2021-02-03 12:11 UTC, snicoll commented on student-bios/selimensar.md
> +I❤️ Web Development!
You could use ❤️  ( `:heart:`)

2021-02-03 16:57 UTC, selimensar commented on student-bios/selimensar.md
> +<div align="center">
Okay, I edited it but I want it to be in the middle of the page.
How can I get all text to the center of the page?

2021-02-03 17:02 UTC, selimensar commented on student-bios/selimensar.md
> +I❤️ Web Development!
Hi Snicol, will you merge my pull request? I could not do it.

2021-02-04 16:56 UTC, snicoll commented on student-bios/selimensar.md
> +<div align="center">
> I want it to be in the middle of the page.

I understand that but the assignment is to write your bio in markdown format. While there are some tricks (like the one you've used) to center the image, please do not over engineer it.

You mentioned you've edited the code but I don't see any change here. Did you push?

2021-02-04 16:57 UTC, snicoll commented on student-bios/selimensar.md
> +I❤️ Web Development!
No I won't. There are changes that I requested and I don't see them.

You can also see by yourself at the bottom of this page that merging is blocked because you need 1 approving review.

2021-02-04 21:43 UTC, selimensar commented on student-bios/selimensar.md
> +<div align="center">
Sorry, I pushed it now :)

2021-02-05 07:19 UTC, snicoll requested changes
Thanks for the update. I've found some HTML still, see below.

2021-02-05 07:19 UTC, snicoll commented on student-bios/selimensar.md
> +<img width="250" src="https://media.giphy.com/media/kFHT64PButf46M7rvP/giphy.gif">
That's not how you should display an image in markdown, that's HTML again.

Please review [the documentation](https://www.markdownguide.org/basic-syntax/#images-1)

2021-02-05 07:19 UTC, snicoll commented on student-bios/selimensar.md
> +I:heart: Web Development!
I'd add a space between `I` and `:heart:`.

2021-02-05 09:02 UTC, selimensar commented on student-bios/selimensar.md
> +<img width="250" src="https://media.giphy.com/media/kFHT64PButf46M7rvP/giphy.gif">
I got it.

2021-02-05 09:06 UTC, snicoll approved these changes
Good job!

2021-02-05 09:07 UTC, merged