Create perezrei bio
HackYourFutureBelgium/class-13-14 pull request #66
Opened 2021-02-04 17:05 UTC by perezrei

2021-02-04 17:16 UTC, snicoll requested changes
Well done Reinaldo!

I've added a comment, can you please look at it? Also, curious if you wrote your bio from the GitHub web interface or if you did this on your machine using a git client. That `patch-1` branch name made me wonder.

2021-02-04 17:16 UTC, snicoll commented on student-bios/perezrei.md
> +<a><img src="https://media.giphy.com/media/LqMn3zJKoi93O/giphy.gif" alt="computer"></a>
Please don't use HTML in your markdown file. There is a way to show an image with Markdown, please [review the documentation](https://www.markdownguide.org/basic-syntax/#images-1).

2021-02-04 19:55 UTC, perezrei commented on student-bios/perezrei.md
> +<a><img src="https://media.giphy.com/media/LqMn3zJKoi93O/giphy.gif" alt="computer"></a>
Hi @snicoll, I did it quite some time ago when I saw a tutorial but you're rigth. There's a command on mardown for that. Do you want me to do another pull request?

2021-02-04 20:21 UTC, perezrei commented on student-bios/perezrei.md
> +<a><img src="https://media.giphy.com/media/LqMn3zJKoi93O/giphy.gif" alt="computer"></a>
Hi @snicoll thanks. You're right. I did it quite some time ago because I watched a video tuturial and it surprised me that the guy was using html commands in markdown. Do you want me to make the change and do another pull request?

2021-02-04 22:25 UTC, perezrei commented on student-bios/perezrei.md
> +<a><img src="https://media.giphy.com/media/LqMn3zJKoi93O/giphy.gif" alt="computer"></a>
I'm sorry that I repeated  the message because my internet was too slow and I thought the first time never got to you. I did it in GitHub and the name of the branch was suggested by default so a I used it. Now, if I want to make some changes like correct the syntaxe of the image using markdown and add a checklist do I have to fork it again? I noticed I forgot to use the label too.

2021-02-05 07:22 UTC, snicoll commented on student-bios/perezrei.md
> +<a><img src="https://media.giphy.com/media/LqMn3zJKoi93O/giphy.gif" alt="computer"></a>
You can delete your own comments by clicking on the 3 dots on the right hand side.

> Do you want me to do another pull request?

That's not how PR works. When a review is made and change is requested, you should update the existing PR rather than creating a new one. If you create a new PR, all the discussions is still on the other issue which makes the task at hand very hard to track.

GitHub informs you on this very page:

> Add more commits by pushing to the perezrei-patch-1 branch on HackYourFutureBelgium/class-13-14.

Can you please tell me if you've created this PR from the GitHub web interface (i.e. if you wrote your bio in your browser)?

2021-02-06 09:29 UTC, closed without merging