My bio Added
HackYourFutureBelgium/class-13-14 pull request #87
Opened 2021-02-09 16:50 UTC by MahmoudHasan83

2021-02-10 09:55 UTC, snicoll requested changes
Great start, I've added a couple comments.

2021-02-10 09:55 UTC, snicoll commented on student-bios/Mahmoud-hasan.md
> +# Profile
The name of the file should be `MahmoudHasan83.md`. Can you please rename it?

2021-02-10 09:55 UTC, snicoll commented on student-bios/Mahmoud-hasan.md
> +<img src="https://user-images.githubusercontent.com/59293654/99892734-462d3e80-2c78-11eb-92d6-47dd2d9b7f7d.jpg" width="150" height="150" />
That's HTML, not markdown. Please review [the reference guide](https://www.markdownguide.org/basic-syntax/#images-1)

2021-02-10 18:15 UTC, MahmoudHasan83 commented on student-bios/Mahmoud-hasan.md
> +# Profile
i noticed that when i uploaded it, i'll fix it now

2021-02-10 18:15 UTC, MahmoudHasan83 commented on student-bios/Mahmoud-hasan.md
> +<img src="https://user-images.githubusercontent.com/59293654/99892734-462d3e80-2c78-11eb-92d6-47dd2d9b7f7d.jpg" width="150" height="150" />
yes i searched a lot in the .md to reduce the image in the .md file but i couldnt find any thing

2021-02-11 08:07 UTC, snicoll commented on student-bios/Mahmoud-hasan.md
> +<img src="https://user-images.githubusercontent.com/59293654/99892734-462d3e80-2c78-11eb-92d6-47dd2d9b7f7d.jpg" width="150" height="150" />
A search on Google refers to [this StackOverflow thread](https://stackoverflow.com/questions/14675913/changing-image-size-in-markdown). The point I was trying to make is to use the tool at hand and not try to over engineer it. If the image is too big you may resize it yourself and post it on a github repo or remove the image altogether by a link to your github profile that has the image already.

2021-02-11 15:36 UTC, MahmoudHasan83 commented on student-bios/Mahmoud-hasan.md
> +<img src="https://user-images.githubusercontent.com/59293654/99892734-462d3e80-2c78-11eb-92d6-47dd2d9b7f7d.jpg" width="150" height="150" />
i tried that way but it didnt work and i thought about resizing the image and upload the resized image but also i read that you can use an html tag inside .md file because this language was intended before for html. if you want me to resize the image and put a link inside i can do it

2021-02-11 16:24 UTC, snicoll commented on student-bios/Mahmoud-hasan.md
> +<img src="https://user-images.githubusercontent.com/59293654/99892734-462d3e80-2c78-11eb-92d6-47dd2d9b7f7d.jpg" width="150" height="150" />
If you want to put an image in your bio, the assignment is to use markdown. Yes, you can use HTML or any other hacks that does the job but that does not necessarily means this is a good idea.

What I'd like you to do is to use the tools the way they are intended. The assignment is about writing a markdown file with your bio.

2021-02-11 16:24 UTC, snicoll approved these changes

2021-02-11 16:31 UTC, merged